@startuml

title UML-діаграма розгортання ПП

left to right direction

skinparam componentStyle uml1

node "<<Mobile phone>>" as dk {
    node "<<Android/iOS>>" {
        node "<<Mobile application>>" {
            component [*.apk]
        }
    }
}

interface sensor as se

interface microphone as mc

interface camera as cm 

se -- dk
mc -- dk
cm -- dk

dk -- serv1
serv1 -- G

node "<<Server 1>>" as serv1 {
	node "<<Windows>>" as l2 {
	    node "<<Aplication server>>" {
		    component [*.jar]
		}
	}
}

node "<<Google cloud platform>>" as G{
	node "<<Firebase>>" as l2 {
	    node "<<Firestore database>>" {
		    database documents
		}
	}
}

@enduml

